PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Name TEXT NOT NULL,
    Hash TEXT NOT NULL,
    FiscalKey INTEGER,
    Role TEXT NOT NULL DEFAULT 'USER' CHECK (Role IN ('USER', 'FISCAL', 'MANAGER'))
);

CREATE TABLE IF NOT EXISTS Items (
    Barcode TEXT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    Price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Operator INTEGER NOT NULL REFERENCES Users (Id),
    Epoch INTEGER NOT NULL,
    Data TEXT NOT NULL,
    Paid INTEGER NOT NULL
);